backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "drinks"
    label: "Drinks"
    files:
      - file: "index.html"
        label: "Homepage"
        name: "homepage"
        fields:
          - label: "Drink 1"
            name: "drink1"
            widget: "string"
          - label: "Drink 2"
            name: "drink2"
            widget: "string"
